#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Note: Windows Bash doesn't support shebang extra params
set -e

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
cd $APP_HOME

source "$APP_HOME/scripts/.functions.sh"

if [[ "$1" != "" ]]; then
    export DOCKER_TAG=testing
fi

echo "The repo name is: " $2


./IoTHubManager/run.sh "IoT Hub Manager tests"

./StorageAdapter/run.sh "Storage Adapter Tests"

./Config/run.sh "Config tests"

./ASAManager/run.sh "ASA Manager tests"

./Telemetry/run.sh "Telemetry tests"

set +e
