// Copyright (c) Microsoft. All rights reserved.

using System.Net;
using System;
using System.Security.Cryptography;
using System.Text;
using Helpers.Http;
using Xunit;
using Newtonsoft.Json.Linq;

namespace IoTHubManager
{
    public class CreateDeviceTest
    {
        private readonly IHttpClient httpClient;
        private const string IOTHUB_ADDRESS = "http://localhost:9002/v1";
        private const string DEVICES_DIR = "./resources/devices/";
        private string DEVICE_TEMPLATE_AUTO_GEN_AUTH, 
                       DEVICE_TEMPLATE_SYMMETRIC_AUTH,
                       DEVICE_TEMPLATE_X509_AUTH;

        public CreateDeviceTest()
        {
            this.httpClient = new HttpClient();
            DEVICE_TEMPLATE_AUTO_GEN_AUTH = System.IO.File.ReadAllText(DEVICES_DIR+"Device_Template_Auto_Generated_Auth.json");
            DEVICE_TEMPLATE_SYMMETRIC_AUTH = System.IO.File.ReadAllText(DEVICES_DIR+"Device_Template_Symmetric_Auth.json");
            DEVICE_TEMPLATE_X509_AUTH = System.IO.File.ReadAllText(DEVICES_DIR+"Device_Template_X509_Auth.json");
                                   
        }

        /// <summary>
        /// Integration test using a real HTTP instance.
        /// Tests for creation of devices with all permutation of AUTH and Id creation
        /// </summary>
        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithAutoGeneratedIdAndSymmetricAuth_FailsOn_EmptyIdOrAuth()
        {
            // DeviceId must be empty to be auto generated.
            var device = DEVICE_TEMPLATE_AUTO_GEN_AUTH.Replace("{DeviceId}","");
            var response = this.request(device);

            // Asserts
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            var createdDevice = JObject.Parse(response.Content);

            var authentication = createdDevice["Authentication"];
            var createdDeviceId = createdDevice["Id"].ToString();

            Assert.False(string.IsNullOrEmpty(createdDeviceId));
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);

            string primaryKey = authentication["PrimaryKey"].ToString(),
                   secondaryKey = authentication["SecondaryKey"].ToString();

            Assert.Equal(0, authentication["AuthenticationType"]);
            Assert.False(string.IsNullOrEmpty(primaryKey));
            Assert.False(string.IsNullOrEmpty(secondaryKey));
            
        }

        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithAutoGenIdAndSymmetricAuth_FailsOn_IncorrectIdOrAuth()
        {
            // DeviceId must be empty to be auto generated.
            string id = Guid.NewGuid().ToString();
            var device = DEVICE_TEMPLATE_AUTO_GEN_AUTH.Replace("{DeviceId}",id);
            var response = this.request(device);

            // Asserts
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            var createdDevice = JObject.Parse(response.Content);

            //Assert Device ID
            string createdDeviceId = createdDevice["Id"].ToString();
            Assert.Equal(createdDeviceId, id);

            //Assert Authentication
            var authentication = createdDevice["Authentication"];
            Assert.Equal(0, authentication["AuthenticationType"]);

            string primaryKey = authentication["PrimaryKey"].ToString(),
                   secondaryKey = authentication["SecondaryKey"].ToString();

            Assert.False(string.IsNullOrEmpty(primaryKey));
            Assert.False(string.IsNullOrEmpty(secondaryKey));

            //Assert other properties
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);
            
        }


        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithCustomIdAndSymmetricAuth_FailsOn_MissingIdOrIncorrectAuth()
        {

            string id = Guid.NewGuid().ToString(),
                   primaryKey = Guid.NewGuid().ToString("n"),
                   secondaryKey = Guid.NewGuid().ToString("n");

            string device = DEVICE_TEMPLATE_SYMMETRIC_AUTH.Replace("{DeviceId}",id)
                                                          .Replace("{PrimaryKey}",primaryKey)
                                                          .Replace("{SecondaryKey}",secondaryKey);
            var response = this.request(device);

            // Asserts
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            var createdDevice = JObject.Parse(response.Content);

            //Assert Device ID is NOT empty
            string createdDeviceId = createdDevice["Id"].ToString();
            Assert.Equal(createdDeviceId, id);

            //Assert Authentication
            var authentication = createdDevice["Authentication"];
            Assert.Equal(0, authentication["AuthenticationType"]);

            string createdPrimaryKey = authentication["PrimaryKey"].ToString(),
                   createdSecondaryKey = authentication["SecondaryKey"].ToString();

            Assert.Equal(primaryKey, createdPrimaryKey);
            Assert.Equal(secondaryKey, createdSecondaryKey);

            //Assert other properties
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);
            
        }


        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithAutoGenIdAndCustomSymmetricAuth_FailsOn_MissingIdOrIncorrectAuth()
        {
            string primaryKey = Guid.NewGuid().ToString("n"),
                   secondaryKey = Guid.NewGuid().ToString("N");
           
            string device = DEVICE_TEMPLATE_SYMMETRIC_AUTH.Replace("{DeviceId}","")
                                                          .Replace("{PrimaryKey}",primaryKey)
                                                          .Replace("{SecondaryKey}",secondaryKey);
            var response = this.request(device);

            // Asserts
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            var createdDevice = JObject.Parse(response.Content);

            //Assert Device ID is NOT empty
            string createdDeviceId = createdDevice["Id"].ToString();
            Assert.False(string.IsNullOrEmpty(createdDeviceId));

            //Assert Authentication
            var authentication = createdDevice["Authentication"];
            Assert.Equal(0, authentication["AuthenticationType"]);

            string createdPrimaryKey = authentication["PrimaryKey"].ToString(),
                   createdSecondaryKey = authentication["SecondaryKey"].ToString();

            Assert.Equal(primaryKey, createdPrimaryKey);
            Assert.Equal(secondaryKey, createdSecondaryKey);

            //Assert other properties
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);
            
        }

        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithCustomIdAndx509Auth_FailsOn_MissingIdOrIncorrectAuth()
        {

            string id = Guid.NewGuid().ToString(),
                   primaryThumbprint = generateNewThumbPrint(),
                   secondaryThumbprint = generateNewThumbPrint();

            string device = DEVICE_TEMPLATE_X509_AUTH.Replace("{DeviceId}",id)
                                                     .Replace("{PrimaryThumbprint}",primaryThumbprint)
                                                     .Replace("{SecondaryThumbprint}",secondaryThumbprint);
            var response = this.request(device);

            //Assert Request success (200 OK)
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            //Parsing JSON
            var createdDevice = JObject.Parse(response.Content);


            //Assert Device ID is NOT empty
            string createdDeviceId = createdDevice["Id"].ToString();
            Assert.Equal(createdDeviceId, id);


            //Assert Authentication
            var authentication = createdDevice["Authentication"];
            Assert.Equal(1, authentication["AuthenticationType"]);

            string createdPrimaryThumbprint = authentication["PrimaryThumbprint"].ToString(),
                   createdSecondaryThumbprint = authentication["SecondaryThumbprint"].ToString();

            Assert.Equal(primaryThumbprint, createdPrimaryThumbprint);
            Assert.Equal(secondaryThumbprint, createdSecondaryThumbprint);


            //Assert other properties
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);
            
        }


        [Fact, Trait("Type", "IntegrationTest")]
        public void Creates_DevicewithAutoGenIdAndCustomx509Auth_FailsOn_MissingIdOrIncorrectAuth()
        {
            string primaryThumbprint = generateNewThumbPrint(),
                   secondaryThumbprint = generateNewThumbPrint();
           
            string device = DEVICE_TEMPLATE_X509_AUTH.Replace("{DeviceId}","")
                                                     .Replace("{PrimaryThumbprint}",primaryThumbprint)
                                                     .Replace("{SecondaryThumbprint}",secondaryThumbprint);
            var response = this.request(device);

            // Asserts
            //Assert Request success (200 OK)
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            //Parsing JSON
            var createdDevice = JObject.Parse(response.Content);


            //Assert Device ID is NOT empty
            string createdDeviceId = createdDevice["Id"].ToString();
            Assert.False(string.IsNullOrEmpty(createdDeviceId));


            //Assert Authentication
            var authentication = createdDevice["Authentication"];
            Assert.Equal(1, authentication["AuthenticationType"]);

            string createdPrimaryThumbprint = authentication["PrimaryThumbprint"].ToString(),
                   createdSecondaryThumbprint = authentication["SecondaryThumbprint"].ToString();

            Assert.Equal(primaryThumbprint, createdPrimaryThumbprint);
            Assert.Equal(secondaryThumbprint, createdSecondaryThumbprint);


            //Assert other properties
            Assert.Equal("false", createdDevice["IsSimulated"]);
            Assert.Equal("true", createdDevice["Enabled"]);
            
        }

        private IHttpResponse request(string content) {
            var request = new HttpRequest(IOTHUB_ADDRESS + "/devices");
            request.SetContent(content);
            return this.httpClient.PostAsync(request).Result;
        }

        /*
        Generates random SHA1 hash mimicing the X509 thumb print
         */
        private string generateNewThumbPrint(){
           
            string input = Guid.NewGuid().ToString();
            SHA1Managed sha = new SHA1Managed();

            var hash = sha.ComputeHash(Encoding.UTF8.GetBytes(input));
            var stringBuilder = new StringBuilder(hash.Length * 2);

            for (int i = 0; i < hash.Length; i++)
            {
                stringBuilder.Append(hash[i].ToString("X2"));
            }

            return stringBuilder.ToString();
        }
    }
}